
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mateusz Woliński (https://sketchfab.com/jeandiz)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/ectoparasitoid-164f696a2008480ba5757b1f905d4bc6
Title: 𝕰𝖈𝖙𝖔𝖕𝖆𝖗𝖆𝖘𝖎𝖙𝖔𝖎𝖉
*/

import { useGLTF, useAnimations } from '@react-three/drei'
import { useEffect, useRef } from 'react'

export default function Model(props) {
    const group = useRef();
  const { nodes, materials, animations } = useGLTF('/scene.gltf');
  const { actions } = useAnimations(animations, group);

  // Автоматически запускаем анимацию "Scene" при загрузке
  useEffect(() => {
    if (actions?.Scene) {
      actions.Scene.play();
    }
  }, [actions]);


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="19c2eb722eb849dd8bb4c0871669b9a6fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Black_Wedding_Dress_001_v01" />
                <group
                  name="humantongue01001"
                  position={[0, 81.831, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="humanTeeth_Base001"
                  position={[0, 81.831, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="humanHighPolyEyes001"
                  position={[0, 81.831, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="humanfemale_generic001"
                  position={[0, 81.831, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="humaneyelashes02001"
                  position={[0, 81.831, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="humaneyebrow001001"
                  position={[0, 81.831, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="humanBody001"
                  position={[0, 81.831, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="human001"
                  position={[0, 81.831, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <group name="Object_13">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_16"
                      geometry={nodes.Object_16.geometry}
                      material={materials['human.tongue01.001']}
                      skeleton={nodes.Object_16.skeleton}
                    />
                    <skinnedMesh
                      name="Object_18"
                      geometry={nodes.Object_18.geometry}
                      material={materials['human.Teeth_Base.001']}
                      skeleton={nodes.Object_18.skeleton}
                    />
                    <skinnedMesh
                      name="Object_20"
                      geometry={nodes.Object_20.geometry}
                      material={materials['human.HighPolyEyes.001']}
                      skeleton={nodes.Object_20.skeleton}
                    />
                    <skinnedMesh
                      name="Object_22"
                      geometry={nodes.Object_22.geometry}
                      material={materials['human.body.001']}
                      skeleton={nodes.Object_22.skeleton}
                    />
                    <skinnedMesh
                      name="Object_24"
                      geometry={nodes.Object_24.geometry}
                      material={materials['human.eyelashes02.001']}
                      skeleton={nodes.Object_24.skeleton}
                    />
                    <skinnedMesh
                      name="Object_26"
                      geometry={nodes.Object_26.geometry}
                      material={materials['human.eyebrow001.001']}
                      skeleton={nodes.Object_26.skeleton}
                    />
                    <skinnedMesh
                      name="Object_396"
                      geometry={nodes.Object_396.geometry}
                      material={materials.Bigbutterfly}
                      skeleton={nodes.Object_396.skeleton}
                    />
                    <group
                      name="Object_15"
                      position={[0, 81.831, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_17"
                      position={[0, 81.831, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_19"
                      position={[0, 81.831, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_21"
                      position={[0, 81.831, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_23"
                      position={[0, 81.831, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_25"
                      position={[0, 81.831, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_395"
                      position={[-0.743, 152.601, 18.534]}
                      rotation={[0.139, 0.028, -3.125]}
                      scale={1.569}
                    />
                  </group>
                </group>
                <group
                  name="Empty"
                  position={[1.15, 119.252, 19.235]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={13.696}
                />
                <group name="Black_Wedding_Dress_001_v01001" />
                <group name="Armature" position={[0.976, -19.656, 6.644]} scale={0.985}>
                  <group name="Object_400">
                    <primitive object={nodes._rootJoint_1} />
                    <skinnedMesh
                      name="Object_433"
                      geometry={nodes.Object_433.geometry}
                      material={materials['Buttons.001']}
                      skeleton={nodes.Object_433.skeleton}
                    />
                    <skinnedMesh
                      name="Object_434"
                      geometry={nodes.Object_434.geometry}
                      material={materials['Buttons.001']}
                      skeleton={nodes.Object_434.skeleton}
                    />
                    <group name="Object_432" position={[0.976, -19.656, 6.644]} scale={0.985} />
                  </group>
                </group>
                <group name="AC_001_Belt001" position={[0.976, -19.656, 6.644]} scale={0.985} />
                <group
                  name="pngimgcom_-_moth_PNG31004"
                  position={[-11.522, 125.539, 32.31]}
                  rotation={[-2.972, 0.612, -2.631]}
                  scale={16.103}
                />
                <group
                  name="pngimgcom_-_moth_PNG31003"
                  position={[7.151, 142.594, 31.621]}
                  rotation={[1.269, 1.396, 0.604]}
                  scale={14.899}
                />
                <group
                  name="pngimgcom_-_moth_PNG31002"
                  position={[-18.082, 139.059, 31.549]}
                  rotation={[-2.707, -0.459, -2.462]}
                  scale={14.044}
                />
                <group
                  name="pngimgcom_-_moth_PNG31001"
                  position={[13.127, 117.432, 38.457]}
                  rotation={[0, 1.293, 0]}
                  scale={8.551}
                />
                <group
                  name="pngimgcom_-_moth_PNG31"
                  position={[-0.362, 120.234, 30.703]}
                  rotation={[Math.PI, -1.467, Math.PI]}
                  scale={8.361}
                />
                <group
                  name="Empty001"
                  position={[-2.157, 116.229, 30.678]}
                  rotation={[-Math.PI / 2, 0, 3.038]}
                  scale={14.044}>
                  <group
                    name="Armature004"
                    position={[0.819, 0.034, 0.322]}
                    rotation={[-0.439, -0.458, -2.147]}
                    scale={0.239}>
                    <group name="Object_443">
                      <primitive object={nodes._rootJoint_2} />
                      <skinnedMesh
                        name="Object_446"
                        geometry={nodes.Object_446.geometry}
                        material={materials.Moth__Texture}
                        skeleton={nodes.Object_446.skeleton}
                      />
                      <group
                        name="Object_445"
                        position={[-11.522, 125.539, 32.31]}
                        rotation={[-2.972, 0.612, -2.631]}
                        scale={16.103}
                      />
                    </group>
                  </group>
                  <group
                    name="Armature003"
                    position={[-0.663, -0.368, 1.972]}
                    rotation={[-1.865, 0, 2.967]}
                    scale={0.221}>
                    <group name="Object_453">
                      <primitive object={nodes._rootJoint_3} />
                      <skinnedMesh
                        name="Object_456"
                        geometry={nodes.Object_456.geometry}
                        material={materials.Moth__Texture}
                        skeleton={nodes.Object_456.skeleton}
                      />
                      <group
                        name="Object_455"
                        position={[7.151, 142.594, 31.621]}
                        rotation={[1.269, 1.396, 0.604]}
                        scale={14.899}
                      />
                    </group>
                  </group>
                  <group
                    name="Armature002"
                    position={[1.315, 0.163, 1.326]}
                    rotation={[-0.02, -0.605, -0.88]}
                    scale={0.209}>
                    <group name="Object_463">
                      <primitive object={nodes._rootJoint_4} />
                      <skinnedMesh
                        name="Object_466"
                        geometry={nodes.Object_466.geometry}
                        material={materials.Moth__Texture}
                        skeleton={nodes.Object_466.skeleton}
                      />
                      <group
                        name="Object_465"
                        position={[-18.082, 139.059, 31.549]}
                        rotation={[-2.707, -0.459, -2.462]}
                        scale={14.044}
                      />
                    </group>
                  </group>
                  <group
                    name="Armature001"
                    position={[-1.138, 0.447, -0.131]}
                    rotation={[0, 0, 2.967]}
                    scale={0.127}>
                    <group name="Object_473">
                      <primitive object={nodes._rootJoint_5} />
                      <skinnedMesh
                        name="Object_476"
                        geometry={nodes.Object_476.geometry}
                        material={materials.Moth__Texture}
                        skeleton={nodes.Object_476.skeleton}
                      />
                      <group
                        name="Object_475"
                        position={[13.127, 117.432, 38.457]}
                        rotation={[0, 1.293, 0]}
                        scale={8.551}
                      />
                    </group>
                  </group>
                  <group name="Armature005" position={[-0.127, -0.02, 0.073]} scale={0.124}>
                    <group name="Object_483">
                      <primitive object={nodes._rootJoint_6} />
                      <skinnedMesh
                        name="Object_486"
                        geometry={nodes.Object_486.geometry}
                        material={materials.Moth__Texture}
                        skeleton={nodes.Object_486.skeleton}
                      />
                      <group
                        name="Object_485"
                        position={[-0.362, 120.234, 30.703]}
                        rotation={[Math.PI, -1.467, Math.PI]}
                        scale={8.361}
                      />
                    </group>
                  </group>
                  <group
                    name="Armature006"
                    position={[-1.03, -0.129, 1.447]}
                    rotation={[-0.821, 0.392, -1.762]}
                    scale={0.095}>
                    <group name="Object_493">
                      <primitive object={nodes._rootJoint_7} />
                      <skinnedMesh
                        name="Object_501"
                        geometry={nodes.Object_501.geometry}
                        material={materials.Moth__Texture}
                        skeleton={nodes.Object_501.skeleton}
                      />
                      <group
                        name="Object_500"
                        position={[11.319, 137.975, 31.755]}
                        rotation={[-2.23, 0.241, 2.661]}
                        scale={6.368}
                      />
                    </group>
                  </group>
                  <group
                    name="Armature007"
                    position={[-0.551, 0.568, 0.552]}
                    rotation={[-0.821, 0.392, 1.554]}
                    scale={0.139}>
                    <group name="Object_503">
                      <primitive object={nodes._rootJoint_8} />
                      <skinnedMesh
                        name="Object_511"
                        geometry={nodes.Object_511.geometry}
                        material={materials.Moth__Texture}
                        skeleton={nodes.Object_511.skeleton}
                      />
                      <group
                        name="Object_510"
                        position={[3.342, 126.118, 41.573]}
                        rotation={[0.831, -0.085, 0.468]}
                        scale={9.369}
                      />
                    </group>
                  </group>
                  <group
                    name="Armature008"
                    position={[1.404, -3.578, 1.694]}
                    rotation={[-0.212, -0.892, 3.086]}
                    scale={0.221}>
                    <group name="Object_513">
                      <primitive object={nodes._rootJoint_9} />
                      <skinnedMesh
                        name="Object_521"
                        geometry={nodes.Object_521.geometry}
                        material={materials.Moth__Texture}
                        skeleton={nodes.Object_521.skeleton}
                      />
                      <group
                        name="Object_520"
                        position={[-12.505, 143.313, -20.428]}
                        rotation={[1.628, 0.687, -1.393]}
                        scale={14.899}
                      />
                    </group>
                  </group>
                  <group
                    name="Armature009"
                    position={[-0.844, -3.433, 1.814]}
                    rotation={[-0.726, 0.476, 2.174]}
                    scale={0.221}>
                    <group name="Object_523">
                      <primitive object={nodes._rootJoint_10} />
                      <skinnedMesh
                        name="Object_531"
                        geometry={nodes.Object_531.geometry}
                        material={materials.Moth__Texture}
                        skeleton={nodes.Object_531.skeleton}
                      />
                      <group
                        name="Object_530"
                        position={[12.025, 145.379, -13.206]}
                        rotation={[0.399, 0.434, 0.605]}
                        scale={14.899}
                      />
                    </group>
                  </group>
                  <group
                    name="Armature010"
                    position={[1.003, -4.355, 2.407]}
                    rotation={[-0.171, -1.28, -2.108]}
                    scale={0.209}>
                    <group name="Object_533">
                      <primitive object={nodes._rootJoint_11} />
                      <skinnedMesh
                        name="Object_541"
                        geometry={nodes.Object_541.geometry}
                        material={materials.Moth__Texture}
                        skeleton={nodes.Object_541.skeleton}
                      />
                      <group
                        name="Object_540"
                        position={[-5.156, 151.627, -30.953]}
                        rotation={[2.787, 0.244, -1.786]}
                        scale={14.044}
                      />
                    </group>
                  </group>
                  <group
                    name="Armature011"
                    position={[0.983, -2.782, 1.307]}
                    rotation={[0.764, -0.831, -0.388]}
                    scale={0.099}>
                    <group name="Object_543">
                      <primitive object={nodes._rootJoint_12} />
                      <skinnedMesh
                        name="Object_551"
                        geometry={nodes.Object_551.geometry}
                        material={materials.Moth__Texture}
                        skeleton={nodes.Object_551.skeleton}
                      />
                      <group
                        name="Object_550"
                        position={[-10.026, 135.82, -10.482]}
                        rotation={[-2.861, -0.575, -1.939]}
                        scale={6.642}
                      />
                    </group>
                  </group>
                  <group
                    name="Armature012"
                    position={[-0.624, -2.801, 1.674]}
                    rotation={[0.26, -0.055, -2.559]}
                    scale={0.116}>
                    <group name="Object_553">
                      <primitive object={nodes._rootJoint_13} />
                      <skinnedMesh
                        name="Object_561"
                        geometry={nodes.Object_561.geometry}
                        material={materials.Moth__Texture}
                        skeleton={nodes.Object_561.skeleton}
                      />
                      <group
                        name="Object_560"
                        position={[10.793, 142.416, -8.344]}
                        rotation={[2.734, 1.082, -2.968]}
                        scale={7.839}
                      />
                    </group>
                  </group>
                </group>
                <group
                  name="pngimgcom_-_moth_PNG31005"
                  position={[11.319, 137.975, 31.755]}
                  rotation={[-2.23, 0.241, 2.661]}
                  scale={6.368}
                />
                <group
                  name="pngimgcom_-_moth_PNG31006"
                  position={[3.342, 126.118, 41.573]}
                  rotation={[0.831, -0.085, 0.468]}
                  scale={9.369}
                />
                <group
                  name="pngimgcom_-_moth_PNG31007"
                  position={[-12.505, 143.313, -20.428]}
                  rotation={[1.628, 0.687, -1.393]}
                  scale={14.899}
                />
                <group
                  name="pngimgcom_-_moth_PNG31008"
                  position={[12.025, 145.379, -13.206]}
                  rotation={[0.399, 0.434, 0.605]}
                  scale={14.899}
                />
                <group
                  name="pngimgcom_-_moth_PNG31009"
                  position={[-5.156, 151.627, -30.953]}
                  rotation={[2.787, 0.244, -1.786]}
                  scale={14.044}
                />
                <group
                  name="pngimgcom_-_moth_PNG31010"
                  position={[-10.026, 135.82, -10.482]}
                  rotation={[-2.861, -0.575, -1.939]}
                  scale={6.642}
                />
                <group
                  name="pngimgcom_-_moth_PNG31011"
                  position={[10.793, 142.416, -8.344]}
                  rotation={[2.734, 1.082, -2.968]}
                  scale={7.839}
                />
                <group
                  name="butterfly2"
                  position={[-0.743, 152.601, 18.534]}
                  rotation={[0.139, 0.028, -3.125]}
                  scale={1.569}
                />
                <group name="Tri" position={[-0.119, 149.801, -7.524]} scale={23.932}>
                  <mesh
                    name="Tri_Material_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tri_Material_0.geometry}
                    material={materials.Material}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')

